 Insert into FIRST_LANGUAGE values (1101,'Noun',12,21,2,3,'ads','tas','tus');
 Insert into FIRST_LANGUAGE values (1102,'Noun',13,22,1,4,'fds','weq','ax');
 Insert into FIRST_LANGUAGE values (1103,'Verb',14,23,2,3,'pitj','morder','bra');
 
 INSERT INTO TRANSCRIPTION(ID, ID_FIRST, ID_GERMAN,KNOWLEDGE_GERWORD, KNOWLEDGE_TRANSCRIPTION,NAME)
 SELECT ID_TRANS, ID,ID_SECOND,0 AS KNOWLEDGE_GERWORD, 0 AS KNOWLEDGE_TRANSCRIPTION,' ' AS NAME FROM FIRST_LANGUAGE
